// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ParsingPipelines",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "ParsingPipelines",
            targets: ["AppModule"],
            bundleIdentifier: "com.rajveersingh.ParsingPipelines",
            teamIdentifier: "98PF56WUUN",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/simibac/ConfettiSwiftUI.git", "1.1.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui")
            ],
            path: "."
        )
    ]
)